name: PassiveWhitelist
version: "${version}"
main: com.bunubbv.passivewhitelist.PassiveWhitelist
api-version: '1.19'
author: bunubbv
website: "https://github.com/bunubbv/PassiveWhitelist"
commands:
  psw:
    usage: '/psw <bypass|reload|revoke>'
permissions:
  psw.bypass:
    default: op
  psw.reload:
    default: op
  psw.revoke:
    default: op
